name: flutter_application_1
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.6
  supabase_flutter: ^2.8.0
  http: ^1.2.1
  flutter_lints: ^3.0.0
  flutter_pdfview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
